on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: 'Install Cloud SDK'
        uses: google-github-actions/setup-gcloud@v0
        with:
          install_components: 'beta,pubsub-emulator'
      - name: 'Start Pub/Sub emulator'
        run: |
          gcloud beta emulators pubsub start --project=testproject &
      - name: Run program
        env:
          PUBSUB_EMULATOR_HOST: 'localhost:8085'
        run: |
          go run main.go
